Workaround for error in rspec-parameterized-table_syntax
```
This version of binding_of_caller doesn't support this version of Ruby

An error occurred while loading ./spec/lib/chatwork/converter_spec.rb.
Failure/Error: false | 0

NoMethodError:
  undefined method 'of_caller' for an instance of Binding

```