Fixed. LoadError: cannot load such file -- bundler/dep_proxy
```
$ bundle exec rake spec
bundler: failed to load command: rake (/home/travis/build/asonas/chatwork-ruby/vendor/bundle/ruby/2.5.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
```

* https://travis-ci.org/asonas/chatwork-ruby/jobs/323556471
* https://github.com/travis-ci/travis-ci/issues/8978